import { describe, expect, it } from 'vitest'

import {
  type ChotShift,
  type ReviewedVisit,
  hasLateDebtApproval,
  shiftIdsWithLateDebtApproval,
  visitDateSpan,
} from '@/lib/shifts/late-debt-approval'

const STATION = 'station-1'
/** 19/08/2026, as `shifts.shift_date` stores it: UTC midnight labelled GMT+7. */
const SHIFT_DATE = new Date('2026-08-19T00:00:00.000Z')

/** A ca of 19/08 chốt'd at 15:30 giờ Việt Nam. */
const chotted: ChotShift = {
  stationId: STATION,
  shiftDate: SHIFT_DATE,
  status: 'completed',
  completedAt: new Date('2026-08-19T08:30:00.000Z'),
}

/** A lượt xe of 19/08 (10:00 giờ Việt Nam), duyệt'd at the given instant. */
function visit(reviewedAt: string | null, over: Partial<ReviewedVisit> = {}): ReviewedVisit {
  return {
    stationId: STATION,
    visitDate: new Date('2026-08-19T03:00:00.000Z'),
    reviewStatus: 'approved',
    reviewedAt: reviewedAt === null ? null : new Date(reviewedAt),
    ...over,
  }
}

describe('hasLateDebtApproval', () => {
  it('flags a ca whose bán nợ was duyệt in the evening, after the 15:30 chốt', () => {
    expect(hasLateDebtApproval(chotted, [visit('2026-08-19T12:00:00.000Z')])).toBe(true)
  })

  it('leaves a ca alone whose bán nợ were all duyệt before it was chốt', () => {
    expect(hasLateDebtApproval(chotted, [visit('2026-08-19T04:00:00.000Z')])).toBe(false)
  })

  // The MISA file is generated by the chốt, so a duyệt at the very same instant is
  // already in it. Late means strictly after.
  it('does not call a duyệt at the exact chốt instant late', () => {
    expect(hasLateDebtApproval(chotted, [visit('2026-08-19T08:30:00.000Z')])).toBe(false)
  })

  it('leaves a ca that was never chốt alone, however late its duyệt', () => {
    const open: ChotShift = { ...chotted, status: 'pending_review', completedAt: null }
    expect(hasLateDebtApproval(open, [visit('2026-08-19T12:00:00.000Z')])).toBe(false)
  })

  it('flags on the one late lượt xe among many early ones', () => {
    expect(
      hasLateDebtApproval(chotted, [
        visit('2026-08-19T04:00:00.000Z'),
        visit('2026-08-19T05:00:00.000Z'),
        visit('2026-08-19T12:00:00.000Z'),
      ])
    ).toBe(true)
  })

  it('has nothing to flag when the ca sold nothing on nợ', () => {
    expect(hasLateDebtApproval(chotted, [])).toBe(false)
  })

  // The same lượt xe the Bán nợ trong ca list and the MISA export select: đã duyệt
  // and đã sửa, this trạm, this ngày. Anything else is not in the file, so its duyệt
  // time cannot make the file wrong.
  it('counts đã sửa beside đã duyệt', () => {
    expect(
      hasLateDebtApproval(chotted, [
        visit('2026-08-19T12:00:00.000Z', { reviewStatus: 'corrected' }),
      ])
    ).toBe(true)
  })

  it('ignores a lượt xe chưa duyệt or đã từ chối', () => {
    expect(
      hasLateDebtApproval(chotted, [
        visit('2026-08-19T12:00:00.000Z', { reviewStatus: 'pending' }),
        visit('2026-08-19T12:00:00.000Z', { reviewStatus: 'needs_review' }),
        visit('2026-08-19T12:00:00.000Z', { reviewStatus: 'rejected' }),
      ])
    ).toBe(false)
  })

  it('ignores a lượt xe of another trạm', () => {
    expect(
      hasLateDebtApproval(chotted, [visit('2026-08-19T12:00:00.000Z', { stationId: 'station-2' })])
    ).toBe(false)
  })

  it('ignores a lượt xe of another ngày', () => {
    expect(
      hasLateDebtApproval(chotted, [
        // 20/08 07:00 giờ Việt Nam — the next ca's day, duyệt'd after this chốt.
        visit('2026-08-20T12:00:00.000Z', { visitDate: new Date('2026-08-20T00:00:00.000Z') }),
      ])
    ).toBe(false)
  })

  // The GMT+7 day runs 17:00Z the day before to 17:00Z of the day itself, the same
  // window the Bán nợ trong ca list uses.
  it('keeps the ngày boundary where the bán nợ list puts it', () => {
    const justInside = visit('2026-08-19T12:00:00.000Z', {
      visitDate: new Date('2026-08-18T17:00:00.000Z'),
    })
    const justOutside = visit('2026-08-19T12:00:00.000Z', {
      visitDate: new Date('2026-08-18T16:59:59.000Z'),
    })
    expect(hasLateDebtApproval(chotted, [justInside])).toBe(true)
    expect(hasLateDebtApproval(chotted, [justOutside])).toBe(false)
  })

  // Rows written before the review columns existed carry no duyệt time; without one
  // there is nothing to compare, so they never flag.
  it('ignores a lượt xe with no duyệt time recorded', () => {
    expect(hasLateDebtApproval(chotted, [visit(null)])).toBe(false)
  })
})

describe('shiftIdsWithLateDebtApproval', () => {
  it('names only the ca that gained a late bán nợ', () => {
    const late = { ...chotted, id: 'shift-late' }
    const clean = {
      ...chotted,
      id: 'shift-clean',
      stationId: 'station-2',
    }
    const ids = shiftIdsWithLateDebtApproval(
      [late, clean],
      [
        visit('2026-08-19T12:00:00.000Z'),
        visit('2026-08-19T04:00:00.000Z', { stationId: 'station-2' }),
      ]
    )
    expect([...ids]).toEqual(['shift-late'])
  })

  it('names nothing when no ca is offered', () => {
    expect(shiftIdsWithLateDebtApproval([], [visit('2026-08-19T12:00:00.000Z')]).size).toBe(0)
  })
})

describe('visitDateSpan', () => {
  it('spans from the first ngày of the list to the end of the last', () => {
    const span = visitDateSpan([
      { shiftDate: new Date('2026-08-19T00:00:00.000Z') },
      { shiftDate: new Date('2026-08-17T00:00:00.000Z') },
    ])
    expect(span).toEqual({
      start: new Date('2026-08-16T17:00:00.000Z'),
      end: new Date('2026-08-19T17:00:00.000Z'),
    })
  })

  it('has no span when there is no ca to bound', () => {
    expect(visitDateSpan([])).toBeNull()
  })
})
